[tool.flake8]
extend-ignore = ['E203']
exclude =[ 
	'.git',
	'__pycache__',
	'docs/source/conf.py','old','build',
	'dist',
	'manage.py',
	'migrations',
	'venv',
	'local_settings.py',
	'settings.py']

max-complexity = 10


[tool.black]
target-version = ['py37']
include = '\.pyi?$'
force-exclude = 'manage.py'

